version: '3'

services:
  supplier:
    build: ./supplier
    image: gpitf/buywolf-supplier
    networks:
      beta_network:
        aliases:
          - frontend
    ports:
      - "8000:8000"
    environment:
      - OIDC_RP_CLIENT_ID
      - OIDC_RP_CLIENT_SECRET
    restart: always

  nginx:
    build: ./nginx
    image: gpitf/buywolf-nginx
    networks:
      - beta_network
    ports:
      - "3000:80"

networks:
  beta_network:
    driver: bridge