version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
    image: gpitf/catalogue-frontend:private-beta
    networks:
      - beta_network
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV
      - BASE_URL
      - OIDC_ISSUER_URL
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
    restart: always

  api:
    image: gpitf/catalogue-api:private-beta
    build: ./api/NHSD.GPITF.BuyingCatalog
    networks:
      - beta_network
    volumes:
      - api_data:/app/Data
    environment:
      - OIDC_ISSUER_URL
    ports:
      - "8001:8001"

  nginx:
    build: ./nginx
    image: gpitf/catalogue-frontend-proxy:private-beta
    networks:
      - beta_network
    ports:
      - "3000:80"

networks:
  beta_network:
    driver: bridge

volumes:
  api_data:
