version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
    image: gpitf/catalogue-frontend:private-beta
    networks:
      - beta_network
    environment:
      - NODE_ENV
      - BASE_URL
      - CACHE_HOST
      - OIDC_ISSUER_URL
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - SESSION_SECRET
    restart: always

  api:
    image: gpitf/catalogue-api:private-beta
    build: ./api/NHSD.GPITF.BuyingCatalog
    networks:
      - beta_network
    environment:
      - OIDC_ISSUER_URL
      - OIDC_USERINFO_URL
      - DATASTORE_CONNECTIONTYPE
      - DATASTORE_CONNECTIONSTRING
      - LOG_CONNECTIONSTRING
      - SHAREPOINT_BASEURL
      - SHAREPOINT_ORGANISATIONSRELATIVEURL
      - SHAREPOINT_LOGIN
      - SHAREPOINT_PASSWORD

  nginx:
    build: ./nginx
    image: gpitf/catalogue-frontend-proxy:private-beta
    networks:
      - beta_network
    ports:
      - "3000:80"
    restart: always

  cache:
    image: redis:alpine
    networks:
      - beta_network
    restart: always

networks:
  beta_network:
    driver: bridge
