version: '3.4'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.deploy

  oidc-provider:
    build:
      context: ./ci-auth-db
    ports:
      - "9000:9000"
    networks:
      - beta_network