version: '3.4'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

  oidc-provider:
    build:
      context: ./ci-auth-db
    image: gpitf/catalogue-oidc-provider:private-beta
    ports:
      - "9000:9000"
    networks:
      - beta_network

  crm:
    build: 
     context: ./crm
    image: gpitf/catalogue-crm:private-beta
    ports:
      - "5001:5001"
    networks:
      - beta_network
    environment:
      - ASPNETCORE_ENVIRONMENT
      - GIF_AUTHORITY_URI
      - GIF_AZURE_CLIENT_ID
      - GIF_ENCRYPTED_CLIENT_SECRET
      - GIF_CRM_URL
      - GIF_CRM_AUTHORITY
