version: '3.4'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.deploy

  oidc-provider:
    build:
      context: ./ci-auth-db
    image: gpitf/catalogue-oidc-provider:private-beta
    ports:
      - "9000:9000"
    networks:
      - beta_network

    crm:
    image: gpitf/catalogue-crm:private-beta
    build: ./crm
    networks:
      - beta_network
    environment:
      - CRM_APIURI
      - CRM_ACCESSTOKENURI
      - CRM_CLIENTID
      - CRM_CLIENTSECRET