apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-api  
  template:
    metadata:
      labels:
        app: bc-pb-app-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-api
        image: buyingcat01.azurecr.io/gpitf/catalogue-api:#{Build.BuildId}#
        ports:
        - containerPort: 5100
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: CACHE_HOST
          value: "cache"
        - name: ASPNETCORE_ENVIRONMENT 
          value: "Development"
        - name: USE_CRM
          value: "true"
        - name: CRM_APIURI
          value: "http://crm:5001/api/"
        - name: CRM_ACCESSTOKENURI
          value: "http://crm:5001/connect/token"          
        - name: CRM_CLIENTID
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTID
        - name: CRM_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTSECRET 
        - name: OIDC_ISSUER_URL
          value: "https://buying-catalogue-beta-prototype.eu.auth0.com"
        - name: OIDC_USERINFO_URL
          value: "https://buying-catalogue-beta-prototype.eu.auth0.com/userinfo"
        - name: OIDC_AUDIENCE
          value: "api.buying-catalogue-beta-prototype"
        - name: SHAREPOINT_BASEURL
          value: "https://hscic365.sharepoint.com/sites/DTGPP/GPITF"
        - name: SHAREPOINT_ORGANISATIONSRELATIVEURL
          value: "Shared Documents/Archive/Buying Catalogue Team Folder/BC Integration"
        - name: SHAREPOINT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_CLIENT_ID
        - name: SHAREPOINT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_CLIENT_SECRET
        - name: SHAREPOINT_LOGIN
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_LOGIN
        - name: SHAREPOINT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_PASSWORD
        - name: DATASTORE_CONNECTIONTYPE
          value: "SqlServer"
        - name: DATASTORE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbdevsecret
              key: DATASTORE_CONNECTIONSTRING        
        - name: LOG_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbdevsecret
              key: LOG_CONNECTIONSTRING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-frontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-frontend
  template:
    metadata:
      labels:
        app: bc-pb-app-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-frontend
        image: buyingcat01.azurecr.io/gpitf/catalogue-frontend:#{Build.BuildId}#
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: ANTIVIRUS_PROVIDER_ENV
          value: "CLAMAV"                  
        - name: BASE_URL
          value: "http://dev.buyingcatalogue.digital.nhs.uk"
        - name: API_BASE_URL
          value: "http://api:5100"
        - name: CACHE_HOST
          value: "cache"        
        - name: DEPLOYED_ENV_LABEL
          value: "#{Build.BuildId}#"         
        - name: OIDC_ISSUER_URL
          value: "https://buying-catalogue-beta-prototype.eu.auth0.com"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bcoidcsecret
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bcoidcsecret
              key: OIDC_CLIENT_SECRET
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-crm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-crm   
  template:
    metadata:
      labels:
        app: bc-pb-app-crm
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-crm
        image: buyingcat01.azurecr.io/gpitf/catalogue-crm:#{Build.BuildId}#
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: CRM_CLIENTID
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTID
        - name: CRM_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTSECRET                     
        - name: GIF_CRM_URL
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_CRM_URL
        - name: GIF_CRM_AUTHORITY
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_CRM_AUTHORITY       
        - name: GIF_AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_AZURE_CLIENT_ID
        - name: GIF_ENCRYPTED_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_ENCRYPTED_CLIENT_SECRET
        - name: LOG_CRM
          value: "true"
        - name: LOG_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbdevsecret
              key: LOG_CONNECTIONSTRING                     
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-nginx  
  template:
    metadata:
      labels:
        app: bc-pb-app-nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-nginx
        image: buyingcat01.azurecr.io/gpitf/catalogue-frontend-proxy:#{Build.BuildId}#
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-cache
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-cache  
  template:
    metadata:
      labels:
        app: bc-pb-app-cache
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-cache
        image: index.docker.io/redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-clamav
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-clamav  
  template:
    metadata:
      labels:
        app: bc-pb-app-clamav
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-clamav
        image: buyingcat01.azurecr.io/gpitf/catalogue-frontend-clamav:#{Build.BuildId}#
        ports:
        - containerPort: 3310
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: MAX_SCAN_SIZE
          value: "1024M"
        - name: MAX_FILE_SIZE
          value: "1024M"
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-mariadb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-mariadb  
  template:
    metadata:
      labels:
        app: bc-pb-app-mariadb
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-mariadb
        image: bitnami/mariadb:latest
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: bcmariadbsecret
              key: MARIADB_USER
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: bcmariadbsecret
              key: MARIADB_DATABASE
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bcmariadbsecret
              key: MARIADB_PASSWORD
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bcmariadbsecret
              key: MARIADB_ROOT_PASSWORD
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-matomo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-matomo  
  template:
    metadata:
      labels:
        app: bc-pb-app-matomo
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-matomo
        image: bitnami/matomo:latest'
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: MARIADB_HOST
          value: "mariadb"
        - name: MARIADB_PORT_NUMBER
          value: "3306"
         - name: MATOMO_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: bcmariadbsecret
              key: MATOMO_DATABASE_USER
        - name: MATOMO_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: bcmariadbsecret
              key: MATOMO_DATABASE_NAME
        - name: MATOMO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bcmariadbsecret
              key: MATOMO_DATABASE_PASSWORD			  
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 5100
  selector:
    app: bc-pb-app-api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 8000
  selector:
    app: bc-pb-app-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: bc-lb-nginx
spec:
  loadBalancerIP: 51.140.70.80
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bc-pb-app-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  ports:
  - port: 6379
  selector:
    app: bc-pb-app-cache
---
apiVersion: v1
kind: Service
metadata:
  name: clamav
spec:
  ports:
  - port: 3310
  selector:
    app: bc-pb-app-clamav    
---
apiVersion: v1
kind: Service
metadata:
  name: crm
spec:
  ports:
  - port: 5001
  selector:
    app: bc-pb-app-crm
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: bc-pb-app-mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: matomo
spec:
  ports:
  - port: 80
  selector:
    app: bc-pb-app-matmo	