apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-api
  namespace: bcprepodenv  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-api  
  template:
    metadata:
      labels:
        app: bc-pb-app-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-api
        image: bcprepodacr.azurecr.io/gpitf/catalogue-api:#{Build.BuildId}#
        ports:
        - containerPort: 5100
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: CACHE_HOST
          value: "cache"
        - name: ASPNETCORE_ENVIRONMENT 
          value: "Production"     
        - name: USE_CRM
          value: "true"
        - name: CRM_APIURI
          value: "http://crm:5001/api/"
        - name: CRM_ACCESSTOKENURI
          value: "http://crm:5001/connect/token"          
        - name: CRM_CLIENTID
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTID
        - name: CRM_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTSECRET   
        - name: OIDC_ISSUER_URL
          value: "https://nhsstore-preprod.eu.auth0.com"
        - name: OIDC_USERINFO_URL
          value: "https://nhsstore-preprod.eu.auth0.com/userinfo"
        - name: OIDC_AUDIENCE
          value: "api.preprod.store.digital.nhs.uk"
        - name: SHAREPOINT_BASEURL
          value: "https://hscic365.sharepoint.com/sites/DTGPP/GPITF"
        - name: SHAREPOINT_ORGANISATIONSRELATIVEURL
          value: "Shared Documents/Archive/Buying Catalogue Team Folder/BC Integration Pre-production"
        - name: SHAREPOINT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_CLIENT_ID
        - name: SHAREPOINT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_CLIENT_SECRET
        - name: SHAREPOINT_LOGIN
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_LOGIN
        - name: SHAREPOINT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bcspsecret
              key: SHAREPOINT_PASSWORD                
        - name: DATASTORE_CONNECTIONTYPE
          value: "SqlServer"
        - name: DATASTORE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbsecret
              key: DATASTORE_CONNECTIONSTRING        
        - name: LOG_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbsecret
              key: LOG_CONNECTIONSTRING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-frontend
  namespace: bcprepodenv  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-frontend
  template:
    metadata:
      labels:
        app: bc-pb-app-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-frontend
        image: bcprepodacr.azurecr.io/gpitf/catalogue-frontend:#{Build.BuildId}#
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: ANTIVIRUS_PROVIDER_ENV
          value: "CLAMAV"        
        - name: BASE_URL
          value: "https://preprod.buyingcatalogue.digital.nhs.uk"
        - name: API_BASE_URL
          value: "http://api:5100"
        - name: CACHE_HOST
          value: "cache"
        - name: DEPLOYED_ENV_LABEL
          value: "#{Build.BuildId}#"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: bcsessionsecret
              key: SESSION_SECRET                    
        - name: OIDC_ISSUER_URL
          value: "https://nhsstore-preprod.eu.auth0.com"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bcoidcsecret
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bcoidcsecret
              key: OIDC_CLIENT_SECRET
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-crm
  namespace: bcprepodenv  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-crm   
  template:
    metadata:
      labels:
        app: bc-pb-app-crm
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-crm
        image: bcprepodacr.azurecr.io/gpitf/catalogue-crm:#{Build.BuildId}#
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: CRM_CLIENTID
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTID
        - name: CRM_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTSECRET                      
        - name: GIF_CRM_URL
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_CRM_URL
        - name: GIF_CRM_AUTHORITY
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_CRM_AUTHORITY                  
        - name: GIF_AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_AZURE_CLIENT_ID
        - name: GIF_ENCRYPTED_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bccrmazuresecret
              key: GIF_ENCRYPTED_CLIENT_SECRET
        - name: LOG_CRM
          value: "true"
        - name: LOG_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbsecret
              key: LOG_CONNECTIONSTRING                           
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-nginx
  namespace: bcprepodenv  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-nginx  
  template:
    metadata:
      labels:
        app: bc-pb-app-nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-nginx
        image: bcprepodacr.azurecr.io/gpitf/catalogue-frontend-proxy:#{Build.BuildId}#
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-cache
  namespace: bcprepodenv  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-cache  
  template:
    metadata:
      labels:
        app: bc-pb-app-cache
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-cache
        image: index.docker.io/redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-clamav
  namespace: bcprepodenv  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-clamav  
  template:
    metadata:
      labels:
        app: bc-pb-app-clamav
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-clamav
        image: bcprepodacr.azurecr.io/gpitf/catalogue-frontend-clamav:#{Build.BuildId}#
        ports:
        - containerPort: 3310
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: MAX_SCAN_SIZE
          value: "1024M"
        - name: MAX_FILE_SIZE
          value: "1024M"             
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: bcprepodenv  
spec:
  ports:
  - port: 5100
  selector:
    app: bc-pb-app-api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bcprepodenv  
spec:
  ports:
  - port: 8000
  selector:
    app: bc-pb-app-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: bc-lb-nginx
  namespace: bcprepodenv  
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:  
  type: LoadBalancer
  loadBalancerIP: 10.240.0.100
  ports:
  - port: 80
  selector:
    app: bc-pb-app-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: bcprepodenv  
spec:
  ports:
  - port: 6379
  selector:
    app: bc-pb-app-cache
---
apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: bcprepodenv  
spec:
  ports:
  - port: 3310
  selector:
    app: bc-pb-app-clamav    
---
apiVersion: v1
kind: Service
metadata:
  name: crm
  namespace: bcprepodenv  
spec:
  ports:
  - port: 5001
  selector:
    app: bc-pb-app-crm 