apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-api  
  template:
    metadata:
      labels:
        app: bc-pb-app-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-api
        image: buyingcat01.azurecr.io/gpitf/catalogue-api
        ports:
        - containerPort: 5100
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: ASPNETCORE_ENVIRONMENT 
          value: "Development"
        - name: OIDC_ISSUER_URL
          value: "https://buying-catalogue-beta-prototype.eu.auth0.com"
        - name: OIDC_USERINFO_URL
          value: "https://buying-catalogue-beta-prototype.eu.auth0.com/userinfo"
        - name: OIDC_AUDIENCE
          value: "api.buying-catalogue-beta-prototype"
        - name: DATASTORE_CONNECTIONTYPE
          value: "SqlServer"
        - name: DATASTORE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbsecret
              key: DATASTORE_CONNECTIONSTRING
        - name: LOG_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: bcdbsecret
              key: LOG_CONNECTIONSTRING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-frontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-frontend
  template:
    metadata:
      labels:
        app: bc-pb-app-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-frontend
        image: buyingcat01.azurecr.io/gpitf/catalogue-frontend
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: BASE_URL
          value: "http://buyingcatprivatebeta.uksouth.cloudapp.azure.com"
        - name: OIDC_ISSUER_URL
          value: "https://buying-catalogue-beta-prototype.eu.auth0.com"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bcoidcsecret
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bcoidcsecret
              key: OIDC_CLIENT_SECRET
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-nginx  
  template:
    metadata:
      labels:
        app: bc-pb-app-nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-private-beta-nginx
        image: buyingcat01.azurecr.io/gpitf/catalogue-frontend-proxy
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-pb-deployment-crm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bc-pb-app-crm   
  template:
    metadata:
      labels:
        app: bc-pb-app-crm
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bc-pribate-beta-crm
        image: buyingcat01.azurecr.io/gpitf/catalogue-crm
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: CRM_APIURI
          value: "https://gifservicedev.azurewebsites.net/api/"
        - name: CRM_ACCESSTOKENURI
          value: "https://gifservicedev.azurewebsites.net/connect/token"
        - name: CRM_CLIENTID
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTID
        - name: CRM_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: bccrmsecret
              key: CRM_CLIENTSECRET         
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 5100
  selector:
    app: bc-pb-app-api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 8000
  selector:
    app: bc-pb-app-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: bc-lb-nginx
spec:
  loadBalancerIP: 51.140.48.244
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bc-pb-app-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: crm
spec:
  ports:
  - port: 5000
  selector:
    app: bc-pb-app-crm