version: '3'

services:
  oidc-provider:
    image: qlik/simple-oidc-provider
    environment:
      USERS_FILE: /config/users.json
      CONFIG_FILE: /config/config.json
    ports:
      - "9000:9000"
    volumes:
      - ./config:/config
